# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f10ae8fcb41b3cd9650df674026bd4d77d6ee7f8a576fc67278effd257846e90f61f88d80a94395544f7ed073823cb754fea70898f51e58067dcc6c5a5ab7fe

test:
  secret_key_base: 48858c39831674f97327686061d19e2c3de6dc702544b9870d729e3d0936812d017fb5e05a5c5b120b248963dad6abe0952c2baab88419cc6d6c04855e2cd436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
