# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb24d37c6086e05afe62a04afa6e1b9f8eec14de22e05024318b9d5fbd0308dd0965db389dd63230525e818b9c84b8d1aae772deac7a3cbd5f3ac2d3d432d758

test:
  secret_key_base: 3284ff2256a498d6d329e4b082dfe174b13d5f1cc7d560f70ae46f373b4ecada09fce32979c67874164fd9ee698a8fb7c42dbab4135366d9916e09357fddfa72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
